// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var Chars, Strings, Types, _, asciiStringType, changeCase, mapStringToNumber,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  _ = Types = require('types.js');

  mapStringToNumber = function(array) {
    var index, j, len, nr, value;
    if (_.notArray(array)) {
      return 0;
    }
    for (index = j = 0, len = array.length; j < len; index = ++j) {
      value = array[index];
      nr = _.forceNumber(value);
      if (nr["void"]) {
        return index;
      }
      array[index] = nr;
    }
    return array.length;
  };

  _ = (function(superClass) {
    extend(_, superClass);

    function _() {
      return _.__super__.constructor.apply(this, arguments);
    }

    _.inRange = function(nr, range) {
      if ((_.isNaN(nr = parseInt(nr, 10))) || (mapStringToNumber(range) < 2)) {
        return false;
      }
      return (nr >= range[0]) && (nr <= range[1]);
    };

    _.limitNumber = function(nr, range) {
      nr = _.forceNumber(nr, 0);
      if (mapStringToNumber(range) < 2) {
        return nr;
      }
      if (nr < range[0]) {
        return range[0];
      }
      if (nr > range[1]) {
        return range[1];
      }
      return nr;
    };

    _.randomNumber = function(min, max) {
      if (mapStringToNumber([min, max]) < 2) {
        return 0;
      }
      if (max < min) {
        return min;
      }
      max = (max - min) + 1;
      return Math.floor((Math.random() * max) + min);
    };

    _.shuffleArray = function(array) {
      var i, j, length, rand, ref, temp;
      if (_.notArray(array) || array.length < 1) {
        return [];
      }
      length = array.length - 1;
      for (i = j = ref = length; ref <= 0 ? j <= 0 : j >= 0; i = ref <= 0 ? ++j : --j) {
        rand = _.randomNumber(0, i);
        temp = array[i];
        array[i] = array[rand];
        array[rand] = temp;
      }
      return array;
    };

    _.positiveIndex = function(index, max) {
      if (0 === (index = _.forceNumber(index, 0))) {
        return false;
      }
      max = Math.abs(_.forceNumber(max));
      if (Math.abs(index) <= max) {
        if (index > 0) {
          return index - 1;
        }
        return max + index;
      }
      return false;
    };

    _.insertSort = function(array) {
      var current, index, j, length, prev, ref;
      length = array.length - 1;
      for (index = j = 1, ref = length; 1 <= ref ? j <= ref : j >= ref; index = 1 <= ref ? ++j : --j) {
        current = array[index];
        prev = index - 1;
        while ((prev >= 0) && (array[prev] > current)) {
          array[prev + 1] = array[prev];
          --prev;
        }
        array[+prev + 1] = current;
      }
      return array;
    };

    _.noDupAndReverse = function(array) {
      var index, j, length, newArr, ref;
      length = array.length - 1;
      newArr = [];
      for (index = j = ref = length; ref <= 0 ? j <= 0 : j >= 0; index = ref <= 0 ? ++j : --j) {
        if (newArr[newArr.length - 1] !== array[index]) {
          newArr.push(array[index]);
        }
      }
      return newArr;
    };

    _.sortNoDupAndReverse = function(array, maxLength) {
      var index, j, len, processed, value;
      processed = [];
      for (index = j = 0, len = array.length; j < len; index = ++j) {
        value = array[index];
        value = _.forceNumber(value);
        if (value["void"]) {
          continue;
        }
        if (value <= maxLength) {
          value = _.positiveIndex(value, maxLength);
        }
        processed.push(_.forceNumber(value, 0));
      }
      return _.noDupAndReverse(_.insertSort(processed));
    };

    return _;

  })(Types);

  Chars = (function(superClass) {
    extend(Chars, superClass);

    function Chars() {
      return Chars.__super__.constructor.apply(this, arguments);
    }

    Chars.ASCII_RANGE_UPPERCASE = [65, 90];

    Chars.ASCII_RANGE_LOWERCASE = [97, 122];

    Chars.ASCII_RANGE_NUMBERS = [48, 57];

    Chars.ASCII_RANGE_SPECIAL_1 = [32, 47];

    Chars.ASCII_RANGE_SPECIAL_2 = [58, 64];

    Chars.ASCII_RANGE_SPECIAL_3 = [91, 96];

    Chars.ASCII_RANGE_SPECIAL_4 = [123, 126];

    Chars.ASCII_RANGE_ALL = [32, 126];

    Chars.REGEXP_SPECIAL_CHARS = ['?', '\\', '[', ']', '(', ')', '*', '+', '.', '/', '|', '^', '$', '<', '>', '-', '&'];

    Chars.ascii = function(ordinal) {
      return String.fromCharCode(_.forceNumber(ordinal));
    };

    Chars.ordinal = function(char) {
      return _.forceNumber(_.forceString(char).charCodeAt(), 0);
    };

    Chars.random = function(range) {
      var max, min;
      range = _.forceArray(range, Chars.ASCII_RANGE_ALL);
      min = _.limitNumber(range[0], range);
      max = _.limitNumber(range[1], range);
      return Chars.ascii(_.randomNumber(min, max));
    };

    return Chars;

  })(_);

  changeCase = function() {
    var arg, args, caseMethod, j, k, len, len1, pos, string;
    string = arguments[0], caseMethod = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    if (string == null) {
      string = '';
    }
    if ('' === (string = _.forceString(string))) {
      return string;
    }
    if ((args.length < 1) || args[0] === void 0) {
      return string[caseMethod]();
    } else if (_.isNumber(args[0])) {
      for (j = 0, len = args.length; j < len; j++) {
        arg = args[j];
        pos = _.positiveIndex(arg, string.length);
        string = Strings.xs(string, function(char, index) {
          if (index === pos) {
            return char[caseMethod]();
          }
          return char;
        });
      }
    } else if (_.isString(args[0])) {
      for (k = 0, len1 = args.length; k < len1; k++) {
        arg = args[k];
        string = Strings.replace(string, arg, arg[caseMethod](), 'gi');
      }
    }
    return string;
  };

  asciiStringType = function(string, method) {
    var char, j, len;
    if ('' === (string = _.forceString(string))) {
      return false;
    }
    for (j = 0, len = string.length; j < len; j++) {
      char = string[j];
      if (!method(char)) {
        return false;
      }
    }
    return true;
  };

  Strings = (function(superClass) {
    extend(Strings, superClass);

    Strings.Types = Types;

    Strings.Chars = Chars;

    Strings.create = function() {
      var arg, j, len, string;
      string = '';
      for (j = 0, len = arguments.length; j < len; j++) {
        arg = arguments[j];
        string += _.forceString(arg);
      }
      return string;
    };

    Strings.get = function() {
      var argsLength, j, length, pos, positions, ref, result, string;
      string = arguments[0], positions = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (arguments.length < 2) {
        return '';
      }
      string = _.forceString(string);
      length = string.length;
      result = '';
      argsLength = arguments.length;
      for (pos = j = 1, ref = argsLength; 1 <= ref ? j <= ref : j >= ref; pos = 1 <= ref ? ++j : --j) {
        pos = _.positiveIndex(arguments[pos], length);
        if (pos !== false) {
          result += string[pos];
        }
      }
      return result;
    };

    Strings.sort = function(string) {
      string = _.forceString(string).trim().split('');
      return _.insertSort(string).join('');
    };

    Strings.random = function(amount, charSet) {
      var i, j, ref, string;
      amount = _.forceNumber(amount, 1);
      string = '';
      for (i = j = 1, ref = amount; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        string += Chars.random(charSet);
      }
      return string;
    };

    Strings.times = function(string, amount) {
      var multi;
      if ('' === (string = _.forceString(string))) {
        return '';
      }
      amount = _.forceNumber(amount, 1);
      multi = '';
      while (amount-- > 0) {
        multi += string;
      }
      return multi;
    };

    Strings.regEscape = function(string) {
      if ('' === (string = _.forceString(string))) {
        return string;
      }
      return Strings.xs(string, function(char) {
        if (indexOf.call(Chars.REGEXP_SPECIAL_CHARS, char) >= 0) {
          return '\\' + char;
        }
        return true;
      });
    };

    Strings.empty = function(string) {
      if (_.notString(string) || (string.length > 0)) {
        return false;
      }
      return true;
    };

    Strings.isAlpha = function(string) {
      if ('' === (string = _.forceString(string))) {
        return false;
      }
      return /^[a-z]*$/ig.test(string);
    };

    Strings.isNumeric = function(string) {
      if ('' === (string = _.forceString(string))) {
        return false;
      }
      return /^[0-9]*$/g.test(string);
    };

    Strings.isAlphaNumeric = function(string) {
      if ('' === (string = _.forceString(string))) {
        return false;
      }
      return /^[0-9|a-z]*$/ig.test(string);
    };

    Strings.isSpecial = function(string) {
      if ('' === (string = _.forceString(string))) {
        return false;
      }
      return /^[^0-9|a-z]*$/ig.test(string);
    };

    Strings.isSpace = function(string) {
      return /^[ \t]+$/g.test(string);
    };

    Strings.hasUpper = function(string) {
      return /[A-Z]+/g.test(string);
    };

    Strings.isUpper = function(string) {
      return /^[A-Z]+$/g.test(string);
    };

    Strings.isLower = function(string) {
      return /^[a-z]+$/g.test(string);
    };

    Strings.xs = function(string, callback) {
      var index, j, length, ref, response, result;
      if (string == null) {
        string = '';
      }
      string = _.forceString(string);
      if (-1 === (length = string.length - 1)) {
        return '';
      }
      callback = _.forceFunction(callback, function(char) {
        return char;
      });
      result = '';
      for (index = j = 0, ref = length; 0 <= ref ? j <= ref : j >= ref; index = 0 <= ref ? ++j : --j) {
        if (response = callback(string[index], index)) {
          if (response === true) {
            result += string[index];
          } else if (_.isStringOrNumber(response)) {
            result += response;
          }
        }
      }
      return result;
    };

    Strings.copy = function(string, offset, amount) {
      offset = _.forceNumber(offset);
      if (('' === (string = _.forceString(string))) || (Math.abs(offset) > string.length)) {
        return '';
      }
      if (offset > 0) {
        offset -= 1;
      }
      return string.substr(offset, _.forceNumber(amount, string.length));
    };

    Strings.replace = function(string, toReplace, replacement, flags) {
      var ref;
      if (string == null) {
        string = '';
      }
      if (toReplace == null) {
        toReplace = '';
      }
      if (replacement == null) {
        replacement = '';
      }
      if (flags == null) {
        flags = 'g';
      }
      if (!(_.isStringOrNumber(string) && ((ref = _["typeof"](toReplace)) === 'string' || ref === 'number' || ref === 'regexp'))) {
        return _.forceString(string);
      }
      if (_.notRegExp(toReplace)) {
        toReplace = Strings.regEscape(toReplace + '');
        toReplace = new RegExp(toReplace, flags);
      }
      return (string + '').replace(toReplace, replacement);
    };

    Strings.trim = function(string) {
      return Strings.replace(string, /^\s+|\s+$/g);
    };

    Strings.trimLeft = function(string) {
      return Strings.replace(string, /^\s+/g);
    };

    Strings.trimRight = function(string) {
      return Strings.replace(string, /\s+$/g);
    };

    Strings.oneSpace = function(string) {
      return Strings.replace(string, /\s+/g, ' ');
    };

    Strings.oneSpaceAndTrim = function(string) {
      return Strings.oneSpace(Strings.trim(string));
    };

    Strings.toCamel = function(string, char) {
      var match;
      string = _.forceString(string);
      char = _.forceString(char, '-');
      match = new RegExp(Strings.regEscape(char) + '([a-z])', 'ig');
      return Strings.replace(string, match, function(all, found) {
        return found.toUpperCase();
      });
    };

    Strings.unCamel = function(string, insertion) {
      string = _.forceString(string);
      insertion = _.forceString(insertion, '-');
      return Strings.replace(string, /([A-Z])/g, insertion + '$1').toLowerCase();
    };

    Strings.shuffle = function(string) {
      string = _.forceString(string);
      return _.shuffleArray((string + '').split('')).join('');
    };

    Strings.find = function(string, toFind, flags) {
      var indices, result;
      indices = [];
      if ('' === (string = _.forceString(string))) {
        return indices;
      }
      flags = _.forceString(flags, 'g');
      if (_.isStringOrNumber(toFind)) {
        toFind = new RegExp(Strings.regEscape(toFind + ''), flags);
      } else if (_.isRegExp(toFind)) {
        toFind = new RegExp(toFind.source, flags);
      } else {
        return indices;
      }
      if (toFind.global) {
        while (result = toFind.exec(string)) {
          indices.push(result.index + 1);
        }
      } else {
        if (result = toFind.exec(string)) {
          indices.push(result.index + 1);
        }
      }
      return indices;
    };

    Strings.count = function(string, toFind) {
      return Strings.find(string, toFind).length;
    };

    Strings.contains = function(string, substring) {
      return Strings.count(string, substring) > 0;
    };

    Strings.between = function(string, before, after) {
      var ref, reg;
      if (!_.allStringOrNumber(string, before, after)) {
        return '';
      }
      before = Strings.regEscape(before + '');
      after = Strings.regEscape(after + '');
      reg = new RegExp(before + '(.+)' + after);
      return ((ref = reg.exec(string + '')) != null ? ref[1] : void 0) || '';
    };

    Strings.slice = function(string, start, size) {
      string = _.forceString(string);
      start = _.forceNumber(start || 1);
      if (false !== (start = _.positiveIndex(start, string.length))) {
        size = _.forceNumber(size);
        return string.slice(start, start + size);
      }
      return '';
    };

    Strings.truncate = function(string, length, appendix) {
      string = _.forceString(string);
      length = _.forceNumber(length, string.length);
      string = Strings.slice(string, 1, length);
      return string + _.forceString(appendix);
    };

    Strings.pop = function(string, amount) {
      string = _.forceString(string);
      amount = _.forceNumber(amount, 1);
      return string.slice(0, -Math.abs(amount));
    };

    Strings.split = function(string, delimiter) {
      var array, j, len, result, word;
      string = Strings.oneSpaceAndTrim(string);
      result = [];
      if (string.length < 1) {
        return result;
      }
      delimiter = _.forceString(delimiter, ' ');
      array = string.split(delimiter[0] || '');
      for (j = 0, len = array.length; j < len; j++) {
        word = array[j];
        if (word.match(/^\s$/)) {
          continue;
        }
        result.push(Strings.trim(word));
      }
      return result;
    };

    Strings.reverse = function(string) {
      var ch, j, length, ref, reversed;
      if (string == null) {
        string = '';
      }
      string = _.forceString(string);
      if ((length = string.length - 1) < 1) {
        return string;
      }
      reversed = '';
      for (ch = j = ref = length; ref <= 0 ? j <= 0 : j >= 0; ch = ref <= 0 ? ++j : --j) {
        reversed += string[ch];
      }
      return reversed;
    };

    Strings.upper = function() {
      var args, string;
      string = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return changeCase.apply(null, [string, 'toUpperCase'].concat(slice.call(args)));
    };

    Strings.lower = function() {
      var args, string;
      string = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return changeCase.apply(null, [string, 'toLowerCase'].concat(slice.call(args)));
    };

    Strings.insert = function() {
      var index, insertion, j, posCount, positions, ref, string;
      string = arguments[0], insertion = arguments[1], positions = 3 <= arguments.length ? slice.call(arguments, 2) : [];
      if (('' === (string = _.forceString(string))) || ('' === (insertion = _.forceString(insertion)))) {
        return string;
      }
      positions = _.sortNoDupAndReverse(positions, string.length);
      posCount = mapStringToNumber(positions) - 1;
      if (0 > posCount) {
        return string;
      }
      for (index = j = 0, ref = posCount; 0 <= ref ? j <= ref : j >= ref; index = 0 <= ref ? ++j : --j) {
        index = positions[index];
        if (index > string.length) {
          string = string + insertion;
          continue;
        }
        string = string.substr(0, index) + insertion + string.substr(index);
      }
      return string;
    };

    Strings.removeRange = function(string, offset, amount) {
      var endpoint;
      string = _.forceString(string);
      if ((string === '') || (false === (offset = _.positiveIndex(offset, string.length))) || (0 > (amount = _.forceNumber(amount, 1)))) {
        return string;
      }
      endpoint = offset + amount;
      return Strings.xs(string, function(char, index) {
        if ((index < offset) || (index >= endpoint)) {
          return true;
        }
      });
    };

    Strings.removePos = function() {
      var pos, positions, string;
      string = arguments[0], positions = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if ('' === (string = _.forceString(string))) {
        return '';
      }
      pos = positions.map(function(value) {
        return _.positiveIndex(value, string.length);
      });
      return Strings.xs(string, function(char, index) {
        if (!(indexOf.call(pos, index) >= 0)) {
          return true;
        }
      });
    };

    Strings.remove = function() {
      var j, len, remove, string, toRemove;
      string = arguments[0], toRemove = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (string == null) {
        string = '';
      }
      if (('' === (string = _.forceString(string))) || (toRemove.length < 1)) {
        return string;
      }
      for (j = 0, len = toRemove.length; j < len; j++) {
        remove = toRemove[j];
        string = Strings.replace(string, remove);
      }
      return string;
    };

    Strings.startsWith = function(string, start) {
      if (('' === (string = _.forceString(string))) || ('' === (start = _.forceString(start)))) {
        return false;
      }
      start = new RegExp('^' + Strings.regEscape(start));
      return start.test(string);
    };

    Strings.endsWith = function(string, ending) {
      if (('' === (string = _.forceString(string))) || ('' === (ending = _.forceString(ending)))) {
        return false;
      }
      ending = new RegExp(Strings.regEscape(ending) + '$');
      return ending.test(string);
    };

    Strings.wrap = function(prepend, append) {
      var wrapper;
      if (prepend == null) {
        prepend = '';
      }
      if (append == null) {
        append = '';
      }
      wrapper = function(string) {
        return Strings.create(prepend, string, append);
      };
      wrapper.wrap = function(outerPrepend, outerAppend) {
        if (outerPrepend == null) {
          outerPrepend = '';
        }
        if (outerAppend == null) {
          outerAppend = '';
        }
        prepend = _.forceString(outerPrepend) + prepend;
        return append += _.forceString(outerAppend);
      };
      return wrapper;
    };

    function Strings() {
      this.set.apply(this, arguments);
      this.wrapMethod = null;
      this.crop = this.slice;
    }

    Strings.prototype.set = function() {
      this.string = Strings.create.apply(this, arguments);
      return this;
    };

    Strings.prototype.sort = function() {
      this.string = Strings.sort(this.string);
      return this;
    };

    Strings.prototype.random = function(amount, charSet) {
      this.string = Strings.random(amount, charSet);
      return this;
    };

    Strings.prototype.xs = function(callback) {
      this.string = Strings.xs(this.string, callback);
      return this;
    };

    Strings.prototype.times = function(times) {
      if (times == null) {
        times = 1;
      }
      this.string = Strings.times(this.string, times);
      return this;
    };

    Strings.prototype.get = function() {
      var j, len, position, string;
      if (arguments.length > 0) {
        string = '';
        for (j = 0, len = arguments.length; j < len; j++) {
          position = arguments[j];
          position = _.positiveIndex(position, this.length);
          if (position !== false) {
            string += this.string[position];
          }
        }
        return string;
      }
      return this.string;
    };

    Strings.prototype.copy = function(offset, amount) {
      return Strings.copy(this.string, offset, amount);
    };

    Strings.prototype.empty = function() {
      return Strings.empty(this.string);
    };

    Strings.prototype.isAlpha = function() {
      return Strings.isAlpha(this.string);
    };

    Strings.prototype.isNumeric = function() {
      return Strings.isNumeric(this.string);
    };

    Strings.prototype.isAlphaNumeric = function() {
      return Strings.isAlphaNumeric(this.string);
    };

    Strings.prototype.isSpecial = function() {
      return Strings.isSpecial(this.string);
    };

    Strings.prototype.isUpper = function() {
      return Strings.isUpper(this.string);
    };

    Strings.prototype.hasUpper = function() {
      return Strings.hasUpper(this.string);
    };

    Strings.prototype.isLower = function() {
      return Strings.isLower(this.string);
    };

    Strings.prototype.isSpace = function() {
      return Strings.isSpace(this.string);
    };

    Strings.prototype.push = function() {
      this.string = this.string + Strings.create.apply(this, arguments);
      return this;
    };

    Strings.prototype.prepend = function() {
      this.string = Strings.create.apply(this, arguments) + this.string;
      return this;
    };

    Strings.prototype.pop = function(amount) {
      this.string = Strings.pop(this.string, amount);
      return this;
    };

    Strings.prototype.insert = function() {
      var positions, string;
      string = arguments[0], positions = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      this.string = Strings.insert.apply(Strings, [this.string, string].concat(slice.call(positions)));
      return this;
    };

    Strings.prototype.trim = function() {
      this.string = Strings.trim(this.string);
      return this;
    };

    Strings.prototype.trimLeft = function() {
      this.string = Strings.trimLeft(this.string);
      return this;
    };

    Strings.prototype.trimRight = function() {
      this.string = Strings.trimRight(this.string);
      return this;
    };

    Strings.prototype.oneSpace = function() {
      this.string = Strings.oneSpace(this.string);
      return this;
    };

    Strings.prototype.oneSpaceAndTrim = function() {
      this.string = Strings.oneSpaceAndTrim(this.string);
      return this;
    };

    Strings.prototype.find = function(string) {
      return Strings.find(this.string, string);
    };

    Strings.prototype.count = function(string) {
      return Strings.count(this.string, string);
    };

    Strings.prototype.contains = function(string) {
      return Strings.contains(this.string, string);
    };

    Strings.prototype.between = function(before, after) {
      return Strings.between(this.string, before, after);
    };

    Strings.prototype.slice = function(start, size) {
      this.string = Strings.slice(this.string, start, size);
      return this;
    };

    Strings.prototype.truncate = function(size, suffix) {
      this.string = Strings.truncate(this.string, size, suffix);
      return this;
    };

    Strings.prototype.remove = function() {
      var strings;
      strings = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      this.string = Strings.remove.apply(Strings, [this.string].concat(slice.call(strings)));
      return this;
    };

    Strings.prototype.removeRange = function(offset, amount) {
      this.string = Strings.removeRange(this.string, offset, amount);
      return this;
    };

    Strings.prototype.removePos = function() {
      var positions;
      positions = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      this.string = Strings.removePos.apply(Strings, [this.string].concat(slice.call(positions)));
      return this;
    };

    Strings.prototype.replace = function(subString, replacement, flags) {
      this.string = Strings.replace(this.string, subString, replacement, flags);
      return this;
    };

    Strings.prototype.reverse = function() {
      this.string = Strings.reverse(this.string);
      return this;
    };

    Strings.prototype.upper = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      this.string = Strings.upper.apply(Strings, [this.string].concat(slice.call(args)));
      return this;
    };

    Strings.prototype.lower = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      this.string = Strings.lower.apply(Strings, [this.string].concat(slice.call(args)));
      return this;
    };

    Strings.prototype.shuffle = function() {
      this.string = Strings.shuffle(this.string);
      return this;
    };

    Strings.prototype.toCamel = function(char) {
      this.string = Strings.toCamel(this.string, char);
      return this;
    };

    Strings.prototype.unCamel = function(insertion) {
      this.string = Strings.unCamel(this.string, insertion);
      return this;
    };

    Strings.prototype.startsWith = function(start) {
      return Strings.startsWith(this.string, start);
    };

    Strings.prototype.endsWith = function(ending) {
      return Strings.endsWith(this.string, ending);
    };

    Strings.prototype.setWrap = function(prepend, append) {
      if (_.isNull(this.wrapMethod)) {
        this.wrapMethod = Strings.wrap(prepend, append);
      } else {
        this.wrapMethod.wrap(prepend, append);
      }
      return this;
    };

    Strings.prototype.removeWrap = function() {
      this.wrapMethod = null;
      return this;
    };

    Strings.prototype.applyWrap = function(prepend, append) {
      this.string = this.setWrap(prepend, append).wrap;
      this.removeWrap();
      return this;
    };

    return Strings;

  })(Chars);

  Object.defineProperty(Strings.prototype, '$', {
    get: function() {
      return this.get();
    }
  });

  Object.defineProperty(Strings.prototype, 'length', {
    get: function() {
      return this.string.length;
    }
  });

  Object.defineProperty(Strings.prototype, 'wrap', {
    get: function() {
      if (!_.isNull(this.wrapMethod)) {
        return this.wrapMethod(this.string);
      }
      return this.string;
    }
  });

  Strings.crop = Strings.slice;

  Strings.prototype.crop = Strings.prototype.slice;

  Strings.prototype.append = Strings.prototype.push;

  if ((typeof define !== "undefined" && define !== null) && ('function' === typeof define) && define.amd) {
    define('strings', [], function() {
      return Strings;
    });
  } else if (typeof module !== "undefined" && module !== null) {
    module.exports = Strings;
  } else if (typeof window !== "undefined" && window !== null) {
    window.Types = Types;
    window.Strings = Strings;
  }

}).call(this);
